### ISSUE TITLE
samples missing.

### ISSUE THREAD

**Issue by netpipe** [Grandbrain/SphinxQt#2]
included model samples to test this with

**Comment by lomakinandrei** [comment]
I don't think it's a good idea to include third party packages in the repository. Acoustic models, even for one language, are too large in size. It is best to use this [tutorial](https://cmusphinx.github.io/wiki/tutorial/) to create your own example. Make sure to create a JSGF language model.

**Comment by netpipe** [comment]
github allows upto 1gb per repository also torrent would even be nice.. just to make that work would take an experienced programmer a day or 2 to get working. i've tried before.
